#!/bin/bash
BAKDIR=~/history
if [ ! -d $BAKDIR ]; then
  mkdir -p $BAKDIR
fi
if [ $# -ge 1 ]; then
  for path in $@; do
    if [ -f $path ]; then
      cp $path $BAKDIR/"$path".`date +%Y-%m-%d.%H-%M-%S`
    elif [ -d $path ]; then
      path=`basename $path`
      tar -cvf $BAKDIR/$path.`date +%Y-%m-%d.%H-%M-%S`.tar $path
    fi
    echo "Backuped $path to $BAKDIR."
  done
fi
