#!/bin/bash
# Network traffic monitor script.

SCALE=2           # Precision of traffic in KB.
INTERVAL=1        # Time interval to collect information.
INTERFACE="eth0"  # Network interface.

while : ; do
  time=`date +"%m-%d %T"`

  line=`ifconfig $INTERFACE | grep "RX bytes"`
  rx_a=`echo $line | awk -F: '{print $2}' | awk '{print $1}'`
  tx_a=`echo $line | awk -F: '{print $3}' | awk '{print $1}'`

  sleep $INTERVAL

  line=`ifconfig eth0 | grep "RX bytes"`
  rx_b=`echo $line | awk -F: '{print $2}' | awk '{print $1}'`
  tx_b=`echo $line | awk -F: '{print $3}' | awk '{print $1}'`

  rx_result=`echo "scale=$SCALE;($rx_b-$rx_a)/1024/$INTERVAL" | bc -l`
  tx_result=`echo "scale=$SCALE;($tx_b-$tx_a)/1024/$INTERVAL" | bc -l`
  echo "$time IN: $rx_result KB/s OUT: $tx_result KB/s"
done
